include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/**.mapper.dart
    - lib/**.realm.dart

linter:
  rules:
    flutter_style_todos: false

