name: mpax_flutter
description: MPax flutter version
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.6.0+7

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  # sudo apt install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
  # sudo pacman gst-plugins-good
  badges: ^3.1.1
  bitsdojo_window: ^0.1.5
  charset: ^1.2.0
  collection: ^1.17.0
  crypto: ^3.0.2
  devicelocale: ^0.6.0
  ffi: ^2.0.1
  # zenity
  file_picker: ^5.2.9
  flex_color_scheme: ^7.0.2
  flutter:
    sdk: flutter
  flutter_image_compress: ^1.1.3
  flutter_lyric:
    git:
      url: https://github.com/realth000/flutter_lyric.git
      ref: master
  fluttertoast: ^8.2.1
  get: ^4.6.5
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  isolate_manager: ^2.2.0+5
  just_audio: ^0.9.32
  metadata_god: ^0.4.1
  on_audio_query:
    git:
      url: https://github.com/realth000/on_audio_query
      path: on_audio_query
      ref: 65eb581b19a27e97fec29c1349fe7ebf18d2c7ab
  path: ^1.8.2
  path_provider: ^2.0.14
  shared_preferences: ^2.1.0
  simple_audio: ^1.5.2
  taglib_ffi:
    path: ./lib/package/taglib_ffi
  url_launcher: ^6.1.10
  watcher: ^1.0.2
  window_manager: ^0.3.2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0
  lint: ^2.0.1

flutter_icons:
  image: assets/images/mpax_flutter_192.png
  windows:
    generate: true
    image_path: "assets/images/mpax_flutter_192.png"
    icon_size: 96

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/mpax_flutter.svg
    - assets/images/mpax_flutter_192.png
    - assets/data/version
    - assets/data/flutter_version
