name: mpax_flutter
description: MPax flutter version
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.6.0+7

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # sudo apt install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
  # sudo pacman gst-plugins-good
  badges: ^3.1.1
  charset: ^2.0.0
  collection: ^1.17.1
  crypto: ^3.0.3
  devicelocale: ^0.6.0
  ffi: ^2.0.2
  # zenity
  file_picker: ^5.2.10
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.0.3
  flutter_lyric:
    git:
      url: https://github.com/realth000/flutter_lyric.git
      ref: master
  flutter_riverpod: ^2.3.6
  fluttertoast: ^8.2.2
  freezed: ^2.4.1
  go_router: ^9.0.3
  hooks_riverpod: ^2.3.6
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  isolate_manager: ^3.0.0
  just_audio: ^0.9.34
  metadata_god: ^0.4.1
  on_audio_query: ^2.9.0
  path: ^1.8.3
  path_provider: ^2.0.15
  responsive_framework: ^1.1.0
  riverpod: ^2.3.6
  shared_preferences: ^2.2.0
  simple_audio: ^1.5.7
  taglib_ffi:
    path: ./lib/package/taglib_ffi
  url_launcher: ^6.1.11
  uuid: ^3.0.7
  watcher: ^1.1.0
  window_manager: ^0.3.4

dev_dependencies:
  build_runner: ^2.4.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  lint: ^2.1.2
  surf_lint_rules: ^1.0.0

flutter_icons:
  image: assets/images/mpax_flutter_192.png
  windows:
    generate: true
    image_path: "assets/images/mpax_flutter_192.png"
    icon_size: 96

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/mpax_flutter.svg
    - assets/images/mpax_flutter_192.png
