name: mpax_flutter
description: MPax music player
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.6.0+7

environment:
  flutter: '>=3.19.0 <4.0.0'
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  # sudo apt install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
  # sudo pacman gst-plugins-good
  bloc: ^8.1.4
  # Blocked by flutter sdk
  collection: any
  dart_mappable: ^4.2.2
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  get_it: ^7.6.9
  go_router: ^13.2.4
  # Blocked by flutter_test
  path: any
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  realm: ^2.0.0
  responsive_framework: ^1.4.0
  slang: ^3.30.2
  slang_flutter: ^3.30.0
  stream_transform: ^2.1.0
  uuid: ^4.4.0
  # taglib_ffi_dart: ^0.0.1
  # taglib_ffi_dart_libs: ^0.0.2
  taglib_ffi_dart:
    path: packages/taglib_ffi_dart/packages/taglib_ffi_dart
  taglib_ffi_dart_libs:
    path: packages/taglib_ffi_dart/packages/taglib_ffi_dart_libs
  fpdart: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.9
  bloc_test: ^9.1.7
  dart_mappable_builder: ^4.2.3
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  slang_build_runner: ^3.30.0
  very_good_analysis: ^5.1.0
  realm_common: ^2.0.0

flutter_icons:
  image: assets/images/mpax_flutter_192.png
  windows:
    generate: true
    image_path: "assets/images/mpax_flutter_192.png"
    icon_size: 96

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/mpax_flutter.svg
    - assets/images/mpax_flutter_192.png
