name: mpax_flutter
description: MPax flutter version
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.6.0+7

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # sudo apt install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
  # sudo pacman gst-plugins-good
  bloc: ^8.1.2
  # Blocked by flutter sdk
  collection: any
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^13.1.0
  # Blocked by flutter_test
  path: any
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  realm: ^1.9.0
  responsive_framework: ^1.1.1
  slang: ^3.29.0
  slang_flutter: ^3.29.0
  stream_transform: ^2.1.0
  uuid: ^4.3.3

dev_dependencies:
  build_runner: ^2.4.8
  bloc_test: ^9.1.5
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  json_serializable: ^6.7.1
  slang_build_runner: ^3.29.0
  very_good_analysis: ^5.1.0

flutter_icons:
  image: assets/images/mpax_flutter_192.png
  windows:
    generate: true
    image_path: "assets/images/mpax_flutter_192.png"
    icon_size: 96

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/mpax_flutter.svg
    - assets/images/mpax_flutter_192.png
