name: mpax_flutter
description: MPax flutter version
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.6.0+7

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # sudo apt install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
  # sudo pacman gst-plugins-good
  charset: ^2.0.1
  collection: any
  crypto: ^3.0.3
  ffi: ^2.1.0
  # zenity
  file_picker: ^6.1.1
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.1.0
  flutter_lyric:
    git:
      url: https://github.com/realth000/flutter_lyric.git
      ref: master
  fluttertoast: ^8.2.4
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  go_router: ^12.1.1
  hooks_riverpod: ^2.4.6
  image_compression: ^1.0.4
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
  isolate_pool_2: ^1.0.6
  metadata_god: ^0.5.2+1
  on_audio_query: ^2.9.0
  open_filex: ^4.3.4
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  responsive_framework: ^1.1.1
  riverpod: ^2.4.6
  riverpod_annotation: ^2.3.1
  shared_preferences: ^2.2.2
  simple_audio: ^1.9.0
  taglib_ffi:
    path: ./package/taglib_ffi
  url_launcher: ^6.2.1
  uuid: ^4.2.1
  watcher: ^1.1.0
  window_manager: ^0.3.7

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
  riverpod_generator: ^3.0.0-dev.2
  riverpod_lint: ^2.3.4
  surf_lint_rules: ^3.0.0

dependency_overrides:
  uuid: ^4.2.1

flutter_icons:
  image: assets/images/mpax_flutter_192.png
  windows:
    generate: true
    image_path: "assets/images/mpax_flutter_192.png"
    icon_size: 96

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/mpax_flutter.svg
    - assets/images/mpax_flutter_192.png
