name: Test build

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      build_android:
        description: Build Android platform artifacts.
        required: true
        type: boolean
        default: true
      build_ios:
        description: Build iOS platform artifacts.
        required: true
        type: boolean
        default: true
      build_linux:
        description: Build Linux platform artifacts.
        required: true
        type: boolean
        default: true
      build_macos:
        description: Build MacOS platform artifacts.
        required: true
        type: boolean
        default: true
      build_windows:
        description: Build Windows platform artifacts.
        required: true
        type: boolean
        default: true
      dry_run:
        description: Dry run, do NOT upload artifacts.
        required: true
        type: boolean
        default: true

env:
  CI_FLUTTER_VERSION: '3.19.x'

jobs:
  build-linux-android:
    name: Build Linux and Android
    if: ${{ github.event_name == 'push' || inputs.build_linux || inputs.build_android }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.CI_FLUTTER_VERSION}}
          cache: true
      - run: |
          sudo apt update -y
          sudo apt install -y ninja-build libgtk-3-dev
      - name: Precompile
        run: |
          git submodule update --init --recursive --force
          flutter pub get
          dart run build_runner build
      - name: Build Linux
        if: ${{ github.event_name == 'push' || inputs.build_linux }}
        run: flutter build linux --release
      - name: Pre Packing
        if: ${{ github.event_name == 'push' || inputs.build_linux }}
        run: |
          pushd build/linux/x64/release/
          mv bundle mpax_flutter
          popd
      - name: Pack Linux tarball
        if: ${{ github.event_name == 'push' || inputs.build_linux }}
        uses: thedoctor0/zip-release@master
        with:
          type: 'tar'
          filename: mpax_flutter-linux.tar.gz
          directory: build/linux/x64/release/
          path: mpax_flutter
      - name: Upload Linux artifacts
        if: ${{ github.event_name != 'push' && inputs.build_linux && !inputs.dry_run }}
        uses: actions/upload-artifact@v3
        with:
          name: mpax_flutter-linux-tarball
          path: build/linux/x64/release/mpax_flutter-linux.tar.gz
      - name: Setup Android sign key
        if: ${{ github.event_name == 'push' || inputs.build_android }}
        run: |
          echo '${{ secrets.KEYSTORE }}' | base64 --decode > android/app/key.jks
          echo '${{ secrets.KEY_PROPERTIES }}' > android/key.properties
      - name: Build Android
        if: ${{ github.event_name == 'push' || inputs.build_android }}
        run: |
          flutter build apk --release
      - name: Pack Android apk
        if: ${{ github.event_name == 'push' || inputs.build_android }}
        run: |
          pushd build/app/outputs/flutter-apk/
          mv app-arm64-v8a-release.apk mpax_flutter-arm64_v8a.apk
          mv app-armeabi-v7a-release.apk mpax_flutter-armeabi_v7a.apk
          popd
      - name: Upload Android artifacts
        if: ${{ github.event_name != 'push' && inputs.build_android && !inputs.dry_run }}
        uses: actions/upload-artifact@v3
        with:
          name: mpax_flutter-apk-arm64_v8a
          path: |
            build/app/outputs/flutter-apk/mpax_flutter-arm64_v8a.apk
  build-windows:
    name: Build Windows
    if: ${{ github.event_name == 'push' || inputs.build_windows }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.CI_FLUTTER_VERSION}}
      - name: Precompile
        run: |
          git submodule update --init --recursive --force
          flutter pub get
          dart run build_runner build
      - name: Build Windows
        run: flutter build windows --release
      - name: Pre Packing
        shell: pwsh
        run: |
          cd build/windows/x64/runner
          Rename-Item Release mpax_flutter
          cd ../../../../
      - name: Pack Windows tarball
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: mpax_flutter-windows.zip
          directory: build/windows/x64/runner
          path: mpax_flutter
      - name: Upload Windows artifacts
        if: ${{ github.event_name != 'push' && !inputs.dry_run }}
        uses: actions/upload-artifact@v3
        with:
          name: mpax_flutter-windows-tarball
          path: build/windows/x64/runner/mpax_flutter-windows.zip
